"""
Scaffold a new Project Euler problem folder from the pe_0000 template.

This script:
1. Copies the pe_0000 template folder into a new pe_XXXX folder.
2. Renames the template Python file to pe_XXXX.py.
3. Fetches the problem title and statement from projecteuler.net.
4. Writes the fetched problem into the new README.md.

Generated by Codex.
"""

from __future__ import annotations

import argparse
import html
import re
import shutil
from pathlib import Path
from typing import Iterable
from urllib.parse import urljoin
from urllib.request import Request, urlopen


BASE_URL = "https://projecteuler.net"
REPO_ROOT = Path(__file__).resolve().parent
TEMPLATE_DIR = REPO_ROOT / "pe_0000"
USER_AGENT = (
    "Mozilla/5.0 (compatible; project-euler-scaffolder/1.0; "
    "+https://projecteuler.net/)"
)


def fetch_text(url: str, timeout: int = 30) -> str:
    """
    Fetch a text response from a URL and decode it using the declared charset.
    """
    request = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(request, timeout=timeout) as response:
        charset = response.headers.get_content_charset() or "utf-8"
        return response.read().decode(charset, errors="replace")


def fetch_problem_title(problem_number: int) -> str:
    """
    Fetch the problem title from the main Project Euler problem page.
    """
    problem_page = fetch_text(f"{BASE_URL}/problem={problem_number}")
    title_match = re.search(r"<h2>\s*(.*?)\s*</h2>", problem_page, re.IGNORECASE | re.DOTALL)
    if title_match is None:
        raise ValueError(f"Could not find a title for problem {problem_number}.")

    title = re.sub(r"<[^>]+>", "", title_match.group(1))
    title = html.unescape(title).strip()
    if not title:
        raise ValueError(f"Received an empty title for problem {problem_number}.")

    return title


def absolutize_relative_links(content: str) -> str:
    """
    Convert relative href/src attributes in HTML content into absolute URLs.
    """
    pattern = re.compile(
        r'(?P<prefix>\b(?:href|src)\s*=\s*["\'])'
        r'(?P<url>[^"\']+)'
        r'(?P<suffix>["\'])',
        re.IGNORECASE,
    )

    def replace(match: re.Match[str]) -> str:
        url = match.group("url")
        if url.startswith(("http://", "https://", "#", "mailto:", "data:")):
            return match.group(0)

        absolute_url = urljoin(f"{BASE_URL}/", url)
        return f'{match.group("prefix")}{absolute_url}{match.group("suffix")}'

    return pattern.sub(replace, content)


def sanitize_statement_content(content: str) -> str:
    """
    Remove UI-only HTML from the fetched statement while preserving structure.
    """
    content = re.sub(
        r'<span\b[^>]*class=["\'][^"\']*\btooltiptext\b[^"\']*["\'][^>]*>.*?</span>',
        "",
        content,
        flags=re.IGNORECASE | re.DOTALL,
    )
    content = re.sub(r'\s(?:class|style)=["\'][^"\']*["\']', "", content, flags=re.IGNORECASE)
    content = re.sub(
        r"<p\b[^>]*>\s*(.*?)\s*</p>",
        lambda match: f"\n\n{match.group(1).strip()}\n\n",
        content,
        flags=re.IGNORECASE | re.DOTALL,
    )
    content = re.sub(r"<p\b[^>]*>", "", content, flags=re.IGNORECASE)
    content = re.sub(r"</p>", "", content, flags=re.IGNORECASE)
    content = absolutize_relative_links(content)
    content = re.sub(r"\n{3,}", "\n\n", content)
    return content.strip()


def fetch_problem_statement(problem_number: int) -> str:
    """
    Fetch the problem statement from the lightweight Project Euler endpoint.
    """
    statement = fetch_text(f"{BASE_URL}/minimal={problem_number}").strip()
    if not statement:
        raise ValueError(f"Could not fetch the statement for problem {problem_number}.")

    return sanitize_statement_content(statement)


def iter_paths_deepest_first(root: Path) -> Iterable[Path]:
    """
    Yield all descendant paths deepest-first so renames happen safely.
    """
    return sorted(root.rglob("*"), key=lambda path: len(path.parts), reverse=True)


def rename_template_paths(target_dir: Path, padded_number: str) -> None:
    """
    Rename copied template files or folders that still contain the 0000 placeholder.
    """
    for path in iter_paths_deepest_first(target_dir):
        if "0000" not in path.name:
            continue

        renamed_path = path.with_name(path.name.replace("0000", padded_number))
        path.rename(renamed_path)


def update_solution_file(solution_path: Path, problem_number: int) -> None:
    """
    Replace problem-number placeholders inside the copied Python template.
    """
    content = solution_path.read_text(encoding="utf-8")
    content = content.replace(
        "Implementation of the solutions for the problem 0 of Project Euler",
        f"Implementation of the solutions for the problem {problem_number} of Project Euler",
        1,
    )
    solution_path.write_text(content, encoding="utf-8")


def build_readme(problem_number: int, title: str, statement: str) -> str:
    """
    Populate the README template with the fetched problem details.
    """
    readme_template = (TEMPLATE_DIR / "README.md").read_text(encoding="utf-8")
    readme = readme_template.replace("# Problem Title", f"# {title}", 1)
    readme = readme.replace("### Problem 0000", f"### Problem {problem_number:04d}", 1)
    readme = readme.replace("Write the problem statement here.", statement, 1)
    return readme


def create_problem(problem_number: int, destination_root: Path | str | None = None) -> Path:
    """
    Create a new problem folder from the pe_0000 template and populate its README.
    """
    if problem_number <= 0:
        raise ValueError("Problem numbers must be positive integers.")

    if not TEMPLATE_DIR.exists():
        raise FileNotFoundError(f"Template folder not found: {TEMPLATE_DIR}")

    destination_root = Path(destination_root) if destination_root is not None else REPO_ROOT
    destination_root.mkdir(parents=True, exist_ok=True)

    padded_number = f"{problem_number:04d}"
    target_dir = destination_root / f"pe_{padded_number}"
    if target_dir.exists():
        raise FileExistsError(f"Refusing to overwrite existing folder: {target_dir}")

    title = fetch_problem_title(problem_number)
    statement = fetch_problem_statement(problem_number)

    shutil.copytree(TEMPLATE_DIR, target_dir)
    rename_template_paths(target_dir, padded_number)

    solution_path = target_dir / f"pe_{padded_number}.py"
    readme_path = target_dir / "README.md"

    if not solution_path.exists():
        raise FileNotFoundError(f"Expected solution file not found: {solution_path}")
    if not readme_path.exists():
        raise FileNotFoundError(f"Expected README file not found: {readme_path}")

    update_solution_file(solution_path, problem_number)
    readme_path.write_text(
        build_readme(problem_number=problem_number, title=title, statement=statement),
        encoding="utf-8",
    )

    return target_dir


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Create a new Project Euler problem folder from the pe_0000 template "
            "and fill its README using projecteuler.net."
        )
    )
    parser.add_argument("problem_number", type=int, help="Project Euler problem number")
    parser.add_argument(
        "--destination-root",
        type=Path,
        default=REPO_ROOT,
        help="Directory where the new pe_XXXX folder should be created",
    )
    args = parser.parse_args()

    try:
        created_path = create_problem(
            problem_number=args.problem_number,
            destination_root=args.destination_root,
        )
    except FileExistsError as exc:
        parser.exit(status=1, message=f"{exc}\n")

    print(f"Created {created_path}")


if __name__ == "__main__":
    main()
